# Site settings
title: "Source"
email: k.chen8880@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Everything radiates out from here. (It's a graph theory joke. A source is a vertex in a digraph with an indegree of 0.)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kchen8880
github_username:  k-chen8888

# Build settings
markdown: kramdown
